### ISSUE TITLE
RCTExceptionsManager.reportFatalException error?

### ISSUE THREAD

**Issue by skleest** [adamjmcgrath/react-native-simple-auth#22] opened 2015-11-04 03:06 UTC
Completely no idea what this means? Thank you.
<img width="371" alt="screen shot 2015-11-03 at 7 04 47 pm" src="https://cloud.githubusercontent.com/assets/13384462/10928509/f2af2170-825d-11e5-9c95-8f41dd56e521.png">

**Comment by adamjmcgrath** [comment] 2015-12-06 15:41
This looks like an issue caused by the libraries react-native dependency clashing with the applications.

Should be fixed by #24 

You may need to do an `npm prune` after install

**Closed as completed by adamjmcgrath** 2015-12-06 15:41 UTC
